name: Build and deploy .NET Core application to Web App payment-gateway

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: paymentGateway
  AZURE_WEBAPP_PACKAGE_PATH: publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build --verbosity normal
    
    - name: Install EF Tool
      run: dotnet tool install --global dotnet-ef
    
    - name: Run Database Migrations
      run: |
        dotnet ef database update \
          --project "${{ env.WORKING_DIRECTORY }}/Payment.csproj" \
          --startup-project "${{ env.WORKING_DIRECTORY }}/Payment.csproj" \
          --context AppDbContext \
          --verbose
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DEV_DB_CONNECTION_STRING }}
      timeout-minutes: 5
    
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" \
          --configuration ${{ env.CONFIGURATION }} \
          --no-build \
          --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: production